---
title: "Homework Graphs"
author: "Ben Sacco and Kathryn Brooks"
date: "April 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
```
```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(gridExtra)
surveys<-read_csv("portal_data_joined.csv")

```




## Average weight compared to sex for Rodents

```{r include=FALSE}
rodent_surveys <- select(surveys, taxa, sex, weight)
head(rodent_surveys)

```

```{r echo=FALSE, paged.print=TRUE}

rodent_surveys2 <- rodent_surveys %>% filter(!is.na(weight))
rodent_surveys <- rodent_surveys2 %>% filter (!is.na(sex))                     

rodent_surveys <- rodent_surveys %>% filter(taxa == "Rodent")
rodent_sex_weight <- rodent_surveys %>%
  group_by(sex) %>%
  summarise(mean_weight= round(mean(weight),digits=2))
ggplot(rodent_sex_weight, aes(x=sex, y=mean_weight)) +
  geom_col()+xlab("SEX") + ylab("AVERAGE WEIGHT")
```

This graph shows the average weights for all rodents in the data set.  We found that for all rodents the average weight was not dependant on sex.